#   当MiGoo 作为外部依赖时，以下配置放入主项目 migoo.yml 文件        ####################################################

# 测试结束后 是否发送邮件  false 不发送
mail.send: false

# 邮箱服务器 imap 地址
mail.imap.host: imap.exmail.qq.com

# 发件人邮箱地址
mail.send.from: your1@email.com

# 发件人邮箱密码
mail.send.password: password

# 收件人列表
mail.send.toList:
  - your@email.com

# 忽略目录
ignore.directory:
  - .svn
  - .git
  - vars.yml
  - vars.yaml
  - vars.properties
