####################################################    框架配置，禁止修改    ####################################################
function.equals:
  - '=='
  - '==='
  - eq
  - equal
  - equals
  - is

function.equalsIgnoreCase:
  - equalsIgnoreCase
  - ignoreCase

function.greaterThanOrEquals:
  - '>='

function.lessThanOrEquals:
  - '<='

function.greaterThan:
  - '>'
  - greater

function.lessThan:
  - '<'
  - less

function.notEquals:
  - '!='
  - '<>'
  - not
  - '!=='

function.contains:
  - contain
  - contains
  - ct
  - ⊆

function.doesNotContains:
  - notContain
  - notContains
  - nc
  - ⊈
  - doesNotContain
  - doesNotContains

function.isEmpty:
  - isEmpty
  - isNull
  - empty
  - blank

function.isNotEmpty:
  - isNotEmpty
  - isNotNull
  - isNotBlank
  - notEmpty
  - notNull
  - notBlank

function.list:
  - list
  - ls
  - listMap
  - lsMap
  - lsm

function.regex:
  - regex

check.json:
  - '^json.[\w]+(.\w+)*'
  - '^body.[\w]+(.\w+)*'
  - '^\$.[\w]+(.\w+)*'

check.body:
  - body
  - content
  - json
  - text
  - html

check.code:
  - line
  - status
  - statusCode
  - statusLine
  - status_code
  - status_line

####################################################    框架配置，禁止修改    ####################################################

#   当MiGoo 作为外部依赖时，以下配置放入主项目 migoo.yml 文件        ####################################################

# 测试结束后 是否发送邮件  false 不发送
mail.send: false

# 邮箱服务器 imap 地址
mail.imap.host: imap.exmail.qq.com

# 发件人邮箱地址
mail.send.from: your1@email.com

# 发件人邮箱密码
mail.send.password: password

# 收件人列表
mail.send.toList:
  - your@email.com

# 忽略目录
ignore.directory:
  - .svn
  - .git
  - vars.yml
  - vars.yaml
  - vars.properties

# 自定义方法变量 扩展类列表
extends.class:
  - xyz.migoo.extender.func.Func